### ISSUE TITLE
Loader ignores tasks on first invocation

### ISSUE THREAD

**Issue by cursork** [boot-clj/boot-bin#1]
This caused confusion for me configuring a project for CI:

1. Download boot.sh as `boot`
2. Run `boot test` in project directory
3. Boot updates itself *but does not run the test task*
4. Boot exits successfully - test run reports false success

The solution I use is to manually call `boot -u` before `boot test`, but I wouldn't expect this to be necessary. And it might catch others out too?

Seems the CLI args are replaced here. https://github.com/boot-clj/boot-bin/blob/d3fbb2923de1d1a3fc80692285b2fcd6e880aafb/src/boot/Loader.java#L244 I'd send a PR but I'm unsure of the best way to do it. The obvious solution of calling `boot.App.main` twice can't happen as it calls `System.exit`.

**Comment by micha** [comment]
What you're seeing is the default behavior when boot doesn't know which version you want. See [here][logic]. Boot tries to determine which `BOOT_VERSION` to use by looking in the following places, in order:

1. `BOOT_VERSION` system property
2. `BOOT_VERSION` environment variable
3. `BOOT_VERSION` property in _./boot.properties_ file
4. `BOOT_VERSION` property in _<project git repo>/boot.properties_ file
5. `BOOT_VERSION` property in _BOOT_HOME/boot.properties_ file
6. the latest cached version of boot

If the boot loader can't find a version to use in any of those places it does the no-op `boot -u` to fetch the latest version of boot and then it exits. I think this is the correct behavior (but of course I could be confused, too) for the following reasons:

* interactive users only see this the very first time they run boot on a new machine---very infrequently
* unattended, automated builds should explicitly set `BOOT_VERSION` to prevent them from breaking unexpectedly from updates to boot itself

[logic]: https://github.com/boot-clj/boot-bin/blob/d3fbb2923de1d1a3fc80692285b2fcd6e880aafb/src/boot/Loader.java#L235-L238

**Comment by micha** [comment]
Also, if you set `BOOT_VERSION` in your project boot won't need to download the default version (2.4.2) and then use that to download the latest version via `boot -u`, which should save more time.

**Comment by Deraen** [comment]
I'm not sure what would be the correct behavior but I guess it makes sense to explicitly set BOOT_VERSION for automated builds. This should just be documented somewhere. Maybe the boot binary should even mention this when it checks the latest version?
