### ISSUE TITLE
Unable to run generated `boot.sh` from current master (e8b3a4e2a)

### ISSUE THREAD

**Issue by brandon-atkinson** [boot-clj/boot-bin#14]
I've been trying to get up and running with the current master and noticed that with my version of bash, I'm unable to run the `boot.sh` output generated by the build.

The failure:
```
$ ./build.sh && ./target/boot.sh
<< Version: latest-8-ge8b3a4e >>
<< Success: bin/boot.sh >>
/usr/local/bin/launch4j
launch4j: Compiling resources
launch4j: Linking
launch4j: Wrapping
WARNING: Sign the executable to minimize antivirus false positives or use launching instead of wrapping.
launch4j: Successfully created ~/boot-bin/target/boot.exe
<< Success: target/boot.exe >>
./target/boot.sh: line 40: options: unbound variable
```

Interestingly, I'm able to run the currently distributed version of 'boot.sh' in the same shell:
```
$ ~/bin/boot --version
#http://boot-clj.com
#Tue Aug 21 00:38:06 EDT 2018
BOOT_CLOJURE_NAME=org.clojure/clojure
BOOT_CLOJURE_VERSION=1.7.0
BOOT_VERSION=2.7.2
```
I dug into it a bit, and it seems to be an issue w/ recent `head.sh` changes. The first issue seems to be that the `set -u` added to protect from access of unset variables is interpreting the empty options array as unset. 

This uncovered another issue, which was that the final exec seemed to be broken by the `${options[@]-}` expansion. The error after fixing the unset variable issue: 

```
$ ./target/boot.sh
Error: Could not find or load main class
```

Removing the trailing dash (which was not part of the working boot.sh currently being distributed) seemed to fix this issue. 

My version of bash:
```
$ $SHELL --version
GNU bash, version 4.4.23(1)-release (x86_64-apple-darwin17.5.0)
```

**Comment by flyboarder** [comment]
This repo is being archived. Future development of the loader for boot-cllj will happen in http://github.com/boot-clj/boot-native
