### ISSUE TITLE
Initial version sync

### ISSUE THREAD

**Issue by rkoeninger** [boot-clj/boot-bin#16]
I noticed the version number in [boot.properties](https://github.com/boot-clj/boot-bin/blob/master/boot.properties#L3) is 2.7.2 when the most recent boot.jar release is 2.8.1.

Does this need to be updated? Does keeping these in sync just part of the process or should the boot executable look up the most recent version when it runs?

I downloaded the latest boot.exe and ran it on my Windows 10 machine and it fetched the 2.7.2 version of boot.jar into `~/.boot/cache`, but `~/.boot/boot.properties` says:

```
#http://boot-clj.com
#Thu Aug 23 18:12:51 EDT 2018
BOOT_CLOJURE_NAME=org.clojure/clojure
BOOT_VERSION=2.8.1
BOOT_CLOJURE_VERSION=1.8.0
```

On the console it outputs:

```
C:\Users\rkoeninger\Workspace
λ boot
Downloading https://github.com/boot-clj/boot/releases/download/2.7.2/boot.jar...
Running for the first time, BOOT_VERSION not set: updating to latest.
Retrieving maven-metadata.xml from https://repo.clojars.org/
#http://boot-clj.com
#Thu Aug 23 18:12:51 EDT 2018
BOOT_CLOJURE_NAME=org.clojure/clojure
BOOT_VERSION=2.8.1
BOOT_CLOJURE_VERSION=1.8.0
```

So it knows 2.8.1 is the most recent version, but it doesn't fetch the 2.8.1 version of the jar? And since 2.8.1 is the most recent version, it appears the executable is already looking up the version, but then downloading the old one.

Is this a known issue, intended behavior or is this worth fixing?

**Comment by flyboarder** [comment]
This repo is being archived. Future development of the loader for boot-cllj will happen in http://github.com/boot-clj/boot-native
