### ISSUE TITLE
java.lang.NoClassDefFoundError: clojure/lang/IFn

### ISSUE THREAD

**Issue by samroberton** [boot-clj/boot-bin#7]
I have a build on CircleCI which started failing today with `java.lang.NoClassDefFoundError: clojure/lang/IFn`.  (It's a private project, sorry, so I can't just point you to a link.)  It's definitely a build issue rather than something I've changed in my project:  rebuilding a previously-green commit (last built 11 August) fails.

My build was installing boot via `curl -fsSLo boot https://github.com/boot-clj/boot-bin/releases/download/latest/boot.sh`.  (That probably wasn't very wise on my part for a CI build, given the lack of repeatability -- I lazily copy/pasted from the boot readme!)

Anyhow, I've managed to get a successful build by changing that download URL in my `circle.yml` from `boot-bin/releases/latest` to `boot-bin/releases/2.5.2`.

I note that regardless of whether I use `boot-bin`'s `latest` or `2.5.2`, it downloads boot `2.5.5` (that is, although `latest` is `boot-bin/releases/2.7.2`, it's still downloading boot `2.5.5`, not the coincidentally-released boot `2.7.2`) -- that sounds a bit suspicious, so perhaps there was a version number that just didn't get updated in `boot-bin` somewhere when the release went out?

If it's not simply that, I can paste the entire stacktrace for the `NoClassDefFoundError` if you like, but I don't believe it's likely to be very instructive.  The error occurs while loading namespaces -- the particular namespace where it's eventually thrown happens to be `org.httpkit.server`:  I'm stabbing in the dark here, but I can't help but notice that that's a namespace that doesn't `require` any other Clojure namespaces.  My guess is that Clojure's been happily following `ns` `require` forms until it gets to this one and then this is the first actual Clojure code other than core that gets loaded.

**Comment by martinklepsch** [comment]
@samroberton Thanks for the report 👍 

Do you set `BOOT_VERSION` in your build environment? This variable affects which version of the various boot versions is loaded. Probably you set this to `2.5.5` which is why you're seeing the jars of version `2.5.5` being downloaded.

For debugging you can try the old `2.5.2` binary against various settings of `BOOT_VERSION`. Same can be done for the `2.7.2` binary.

Hope that helps

**Comment by samroberton** [comment]
Ah, crap!  I looked for that, and it wasn't in my `circle.yml`.  But now that I look harder, there's a `boot.properties` that is indeed included in CI as well.

Sorry for the noise, and thanks for the response!

**Comment by martinklepsch** [comment]
No problem :) Just for reference what was the version of boot you specified in your `boot.properties` file?

**Comment by samroberton** [comment]
I did indeed have `BOOT_VERSION=2.5.5`.  (And my solution for the moment is to leave that there, and to leave the `boot-bin` download pinned to to the `2.5.2` release URL.)

**Comment by martinklepsch** [comment]
@samroberton if you could try the following combinations that would be great:

- `BOOT_VERSION=2.7.2` and `boot-bin` left at `2.5.2`
- `BOOT_VERSION=2.7.2` and `boot-bin` upgraded to `2.7.2`

As far as I know both should work fine as long as you're not using Java 9. For Java 9  you are required to use boot-bin `2.7.2`.

**Comment by samroberton** [comment]
Both of those combinations give me green builds.

**Comment by martinklepsch** [comment]
Awesome, thanks a lot for trying them out. That gives some confidence that things are working as they should :)
