### ISSUE TITLE
Cut a release using launch4j 3.11 for better Java 9 support on Windows

### ISSUE THREAD

**Issue by fredZen** [boot-clj/boot-bin#8]
Hi,

Because of changes in how Java uses the registry, the version of launch4j you’re using (3.8) can’t see java 9.

Can you upgrade to launch4j 3.11, which has at least ‘basic java 9 support’?

**Comment by martinklepsch** [comment]
I recently tested Boot on Java 9 and didn't have any issues. Is this specific to a particular platform?

**Comment by fredZen** [comment]
As far as I can tell, only the windows version of boot depends on launch4j

**Comment by fredZen** [comment]
If there’s anything I can do to help resolve this issue, will you let me know?

**Comment by martinklepsch** [comment]
@fredZen I'm not too familiar with launch4j and Windows, is it simply a matter of installing a version of launch4j above 3.11 on my system and building `boot.exe` using that?

**Comment by fredZen** [comment]
That’s the idea. For some reason, build.sh didn’t produce boot.exe, or maybe it did but not in the place where I was expecting it. So I manually 

- opened the launch4j GUI, 
- opened launch4j-config.xml, 
- replaced the `output file` and `jar` path with absolute paths, just to be sure
- and built the wrapper

I can confirm that the resulting boot.exe works with Java 9. I’d be happy to upload it somewhere – but then again, I’m a random stranger on the internet, so I’ll understand if you don’t take me up on the offer!

**Comment by fredZen** [comment]
For completeness’ sake, my steps to build on a windows machine:

- Install an 1.7 JDK (build.sh insists on it and I didn’t have one already)
- find some implementation of bash for windows - I used git bash
- because I didn’t have wget at hand, manually download `https://github.com/boot-clj/boot-bin/releases/download/2.4.2/boot.sh` and save it as `build/boot` (relative to `build.sh`'s directory)
- run `build.sh`, this produces `target/loader.jar`
- manually build the .exe from the .jar (see comment above)
- do a victory dance

**Comment by martinklepsch** [comment]
@fredZen thanks for looking into this and being willing to contribute 🙌 

I found these lines in `build.sh`: https://github.com/boot-clj/boot-bin/blob/817fd0f4389b985139dda2298ed549172b77abf5/build.sh#L29-L34

Did you see a message that boot.exe has been skipped? 

I ended up installing `launch4j` using `brew install launch4j` and was able to create both, `boot.sh` and `boot.exe`. I'll look into creating a release with an updated version of launch4j soon.

**Comment by fredZen** [comment]
Cool!

I actually got 'Success: bin/boot.exe', it’s quite possible that launch4j built the exe but stored it... somewhere?

I feel a little silly now for assuming I needed to be on a windows box to build boot.exe, it appears I could have done it from one of the linux machine and saved me a bunch of trouble :-)

Anyway, thank you so much for looking into this @martinklepsch !

**Comment by jaccarmac** [comment]
I'm using the most recent version of the boot executable and it doesn't like the newer JDK. Was the release cut from the latest l4j release which supports Java 9+? I see that it was released after 3.12 was out but can't confirm whether that's what's in the EXE or not

**Comment by flyboarder** [comment]
This repo is being archived. Future development of the loader for boot-cllj will happen in http://github.com/boot-clj/boot-native
