### ISSUE TITLE
Revisit install function code

### ISSUE THREAD

**Issue by martinklepsch** [boot-clj/boot-bin#9]
```java
public static File
install(String version) throws Exception {
    Properties p  = propertiesResource("boot/tag-release.properties");
    String     v  = p.getProperty(version);
    String     vv = (v == null) ? version : v;
    String     nn = "boot." + ((v == null) ? "jar" : "sh");
    return download(downloadUrl(vv, nn), binaryFileCreate(vv)); }
```

These files are downloaded from https://github.com/boot-clj/boot/releases/ — since version [2.4.0](https://github.com/boot-clj/boot/releases/tag/2.4.0) those releases no longer contain any `.sh` or `.exe` files. 

As I understand boot-bin only needs to download `boot.jar` (i.e. boot/base)?

**Comment by martinklepsch** [comment]
Seems it's needed for versions listed in https://github.com/boot-clj/boot-bin/blob/master/resources/boot/tag-release.properties but I don't fully understand what's going on here...

**Comment by arichiardi** [comment]
@martinklepsch I think it's correct that we don't have any `.sh` anymore. You are suppose to download it with `wget` once and the the `-u/-U` downloads only the latest `.jar` for you. So maybe the above is not needed anymore? @micha might confirm or deny this :smile:
